FROM python:3.8-slim

# Install pip and other dependencies
RUN apt-get update && apt-get install -y python3-pip

# Set working directory in the container
WORKDIR /app

# Copy requirements.txt
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application
COPY . /app/

CMD ["python3", "src/training.py"]